<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 19-10-2020
 * Time: 12:10
 * Path: /secure/com/settings/Settings.php
 */

namespace OrSdk\Models\Com\Settings;

use OrSdk\Models\BaseModels;

class Settings extends BaseModels
{
    public $id;
    public $companyRegistrationNo;
    public $name;
    public $add1;
    public $add2;
    public $postalZone;
    public $city;
    public $mail;
    public $contactName;
    public $www;
    public $mobile;
    public $nextInvoiceNo;
    public $prefixInvoiceNo;
    public $postfixInvoiceNo;
    public $zeroPadInvoiceNo;
    public $invoiceLogo;
    public $debtorAccountsId;
    public $creditorAccountsId;
    public $defaultBankAccountsId;
    public $resultAccountsId;
    public $analysisAccountsId;
    public $vatSales;
    public $vatPurchase;
    public $vatGoodsIntPurchase;
    public $vatServicesIntPurchaseReversePayment;
    public $vatOilAndBottledGas;
    public $vatElectricity;
    public $vatNaturalAndCityGas;
    public $vatCoal;
    public $vatCarbonEmission;
    public $vatWater;
    public $vatSettlement;
    public $sendAsAttachment;
    public $currentTemplate;
    public $defaultJournalAccountsId1;
    public $defaultJournalAccountsId2;
    public $defaultJournalAccountsId3;
    public $nextJournalId;
    public $defaultPaymentDays;
    public $businessForm;
    public $vatRegistration;
    public $reportOrderDirection;
    public $reportAmountDisplay;
    public $interestFeeAccountId;
}