<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 08-03-2023
 * Time: 11:03
 * Path: /secure/com/subscribed_apps/SubscribedApps.php
 */

namespace OrSdk\Models\Com\SubscribedApps;


use OrSdk\Models\BaseModels;

class SubscribedApps extends BaseModels
{
    public $id;
    public $publicParams;
    public $privateParams;
    public $state;
    public $paramTestCallback;
}