<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 19-10-2020
 * Time: 12:10
 * Path: /secure/com/settings/Settings.php
 */

namespace OrSdk\Models\Com\Settings;

use OrSdk\Models\BaseModels;

class Settings extends BaseModels
{
    public ?string $id                                   = null;
    public ?string $companyRegistrationNo                = null;
    public ?string $name                                 = null;
    public ?string $add1                                 = null;
    public ?string $add2                                 = null;
    public ?string $postalZone                           = null;
    public ?string $city                                 = null;
    public ?string $mail                                 = null;
    public ?string $contactName                          = null;
    public ?string $www                                  = null;
    public ?string $mobile                               = null;
    public ?string $nextInvoiceNo                        = null;
    public ?string $prefixInvoiceNo                      = null;
    public ?string $postfixInvoiceNo                     = null;
    public ?string $zeroPadInvoiceNo                     = null;
    public ?string $invoiceLogo                          = null;
    public ?string $debtorAccountsId                     = null;
    public ?string $creditorAccountsId                   = null;
    public ?string $defaultBankAccountsId                = null;
    public ?string $resultAccountsId                     = null;
    public ?string $analysisAccountsId                   = null;
    public ?string $vatSales                             = null;
    public ?string $vatPurchase                          = null;
    public ?string $vatGoodsIntPurchase                  = null;
    public ?string $vatServicesIntPurchaseReversePayment = null;
    public ?string $vatOilAndBottledGas                  = null;
    public ?string $vatElectricity                       = null;
    public ?string $vatNaturalAndCityGas                 = null;
    public ?string $vatCoal                              = null;
    public ?string $vatCarbonEmission                    = null;
    public ?string $vatWater                             = null;
    public ?string $vatSettlement                        = null;
    public ?string $sendAsAttachment                     = null;
    public ?string $currentTemplate                      = null;
    public ?string $defaultJournalAccountsId1            = null;
    public ?string $defaultJournalAccountsId2            = null;
    public ?string $defaultJournalAccountsId3            = null;
    public ?string $nextJournalId                        = null;
    public ?string $defaultPaymentDays                   = null;
    public ?string $businessForm                         = null;
    public ?string $vatRegistration                      = null;
    public ?string $reportOrderDirection                 = null;
    public ?string $reportAmountDisplay                  = null;
    public ?string $interestFeeAccountId                 = null;
    public ?string $eDeliveryNotice                      = null;
    public ?string $customHtmlHead                       = null;
    public ?string $defaultDocumentNote                  = null;
    public ?string $journalCalcIncludeAll                = null;
}