<?php

/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 04-10-2019
 * Time: 06:10
 * Path: /secure/com/currencies/Currencies.php
 */

namespace OrSdk\Models\Com\Currencies;

use OrSdk\Models\BaseModels;

class Currencies extends BaseModels
{
    public $currencyCode;
    public $currencyExchangeRate;
    public $currencyName;
    public $id;
}
