<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 12-09-2019
 * Time: 12:09
 * Path: /secure/com/vat_codes/VatCodes.php
 */

namespace OrSdk\Models\Com\VatCodes;

use OrSdk\Models\BaseModels;


class VatCodes extends BaseModels
{
    public ?string $id               = null;
    public ?string $code             = null;
    public ?string $name             = null;
    public ?string $rate             = null;
    public ?string $accountsId       = null;
    public ?string $type             = null;
    public ?string $contraAccountsId = null;
    public ?string $vatSection       = null;
    public ?string $active           = null;
    public ?string $deductionRate    = null;
    public ?string $readOnly         = null;
    public ?string $calculation      = null;
    public ?string $description      = null;
}