<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 20-09-2019
 * Time: 06:09
 * Path: /secure/com/items/Items.php
 */

namespace OrSdk\Models\Com\Items;

use OrSdk\Models\BaseModels;

class Items extends BaseModels
{
    public $id;
    public $articleType;
    public $articleNo;
    public $name;
    public $unit;
    public $price;
    public $vat;
    public $accountsId;
    public $active;
}
