<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 24-09-2020
 * Time: 01:09
 * Path: /secure/com/journals/Journals.php
 */

namespace OrSdk\Models\Com\Journals;

use OrSdk\Models\BaseModels;

class Journals extends BaseModels
{
    public $id;
    public $name;
    public $type;
}