<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 08-03-2023
 * Time: 11:47
 * Path: /secure/com/reconciliations_new/ReconciliationsNew.php
 */

namespace OrSdk\Models\Com\ReconciliationsNew;

use OrSdk\Models\BaseModels;


class ReconciliationsNew extends BaseModels
{
    public $id;
    public $reconciliationsKey;
    public $entriesId;
    public $amount;
}