<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 16-09-2019
 * Time: 05:09
 * Path: /secure/com/document_notes/DocumentNotes.php
 */

namespace OrSdk\Models\Com\DocumentNotes;

use OrSdk\Models\BaseModels;


class DocumentNotes extends BaseModels
{
    public $id;
    public $timestamp;
    public $docId;
    public $noteDa;
    public $noteBlob;
}

