<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 05-10-2020
 * Time: 01:10
 * Path: /secure/com/entries/Entries.php
 */

namespace OrSdk\Models\Com\Entries;

use OrSdk\Models\BaseModels;


class Entries extends BaseModels
{
    public $id;
    public $entryDate;
    public $amount;
    public $amountCurrency;
    public $currencyIso;
    public $currencyRate;
    public $voucherNo;
    public $accountsId;
    public $vat_codesId;
    public $text;
    public $additionalText;
    public $contactsId;
    public $documentsId;
    public $discountPercent;
    public $articleNo;
    public $quantity;
    public $unit;
    public $dueDate;
    public $entryType;
    public $counterEntryId;
    public $prime;
    public $status;
    public $vatJournalId;
    public $documentsSubId;
    public $unitPrice;
    public $documentPosition;
    public $itemsId;
    public $vatSettled;
}