<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 09-11-2020
 * Time: 02:11
 * Path: /secure/com/documents/Documents.php
 */

namespace OrSdk\Models\Com\Documents;

use OrSdk\Util\dataType;
use OrSdk\Util\BasicEnum;

use OrSdk\Models\BaseModels;


class Documents extends BaseModels
{
    public $id;
    public $documentType;
    public $name;
    public $dataHtml;
    public $dataPdf;
    public $dataOioubl;
    public $paymentNotificationSend;
    public $reminderState;
    public $lastReminderDate;
    public $vatPeriodStart;
    public $vatPeriodEnd;
    public $documentIdentifier;
    public $documentDate;
    public $paymentDate;
    public $deliveryDate;
    public $paymentMethod;
    public $dispatchMethod;
    public $endpoint;
    public $contactsId;
    public $currency;
    public $senderName;
    public $senderAdd1;
    public $senderAdd2;
    public $senderCity;
    public $senderPostalCode;
    public $senderContact;
    public $senderCompanyReg;
    public $senderPhone;
    public $senderEmail;
    public $buyersOrderId;
    public $sellersOrderId;
    public $cardTypeOrBankReg;
    public $paymentIdentiferOrAccount;
    public $creditorNumberOrBankName;
    public $documentNote;
    public $attachmentPdf;
    public $documentOutId;
    public $dueDateMethod;
    public $daysAfterBasis;
    public $documentStatus;
    public $journalId;
}

class DocumentsTypes extends BasicEnum
{
    const id                       	= dataType::INT;
    const documentType             	= dataType::ENUM;
    const name                     	= dataType::VARCHAR;
    const dataHtml                 	= dataType::LONGBLOB;
    const dataPdf                  	= dataType::LONGBLOB;
    const dataOioubl               	= dataType::LONGBLOB;
    const paymentNotificationSend  	= dataType::ENUM;
    const reminderState            	= dataType::ENUM;
    const lastReminderDate         	= dataType::DATE;
    const vatPeriodStart           	= dataType::DATE;
    const vatPeriodEnd             	= dataType::DATE;
    const documentIdentifier       	= dataType::VARCHAR;
    const documentDate             	= dataType::DATE;
    const paymentDate              	= dataType::DATE;
    const deliveryDate             	= dataType::DATE;
    const paymentMethod            	= dataType::INT;
    const dispatchMethod           	= dataType::ENUM;
    const endpoint                 	= dataType::VARCHAR;
    const contactsId               	= dataType::INT;
    const currency                 	= dataType::VARCHAR;
    const senderName               	= dataType::VARCHAR;
    const senderAdd1               	= dataType::VARCHAR;
    const senderAdd2               	= dataType::VARCHAR;
    const senderCity               	= dataType::VARCHAR;
    const senderPostalCode         	= dataType::VARCHAR;
    const senderContact            	= dataType::VARCHAR;
    const senderCompanyReg         	= dataType::VARCHAR;
    const senderPhone              	= dataType::VARCHAR;
    const senderEmail              	= dataType::VARCHAR;
    const buyersOrderId            	= dataType::VARCHAR;
    const sellersOrderId           	= dataType::VARCHAR;
    const cardTypeOrBankReg        	= dataType::VARCHAR;
    const paymentIdentiferOrAccount	= dataType::VARCHAR;
    const creditorNumberOrBankName 	= dataType::VARCHAR;
    const documentNote             	= dataType::TEXT;
    const attachmentPdf            	= dataType::LONGBLOB;
    const documentOutId            	= dataType::INT;
    const dueDateMethod            	= dataType::ENUM;
    const daysAfterBasis           	= dataType::INT;
    const documentStatus           	= dataType::ENUM;
    const journalId                	= dataType::INT;
}

abstract class DocumentType extends BasicEnum
{
    const income       	= 'income';
    const expense      	= 'expense';
    const finance      	= 'finance';
    const bankstatement	= 'bankstatement';
    const vatreport    	= 'vatreport';
    const subdocument  	= 'subdocument';
    const reminder     	= 'reminder';
}

abstract class PaymentNotificationSend extends BasicEnum
{
    const yes	= 'yes';
    const no 	= 'no';
}

abstract class ReminderState extends BasicEnum
{
    const none        	= 'none';
    const warned      	= 'warned';
    const _1          	= '1';
    const _2          	= '2';
    const _3          	= '3';
    const collect     	= 'collect';
    const collectsleep	= 'collectsleep';
    const collectended	= 'collectended';
}

abstract class DispatchMethod extends BasicEnum
{
    const email    	= 'email';
    const GLN      	= 'GLN';
    const snailMail	= 'snailMail';
}

abstract class DueDateMethod extends BasicEnum
{
    const net  	= 'net';
    const month	= 'month';
}

abstract class DocumentStatus extends BasicEnum
{
    const payed   	= 'payed';
    const notPayed	= 'notPayed';
    const failed  	= 'failed';
}