<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 05-10-2020
 * Time: 01:10
 * Path: /secure/com/entries/Entries.php
 */

namespace OrSdk\Models\Com\Entries;

use OrSdk\Util\dataType;
use OrSdk\Util\BasicEnum;

use OrSdk\Models\BaseModels;


class Entries extends BaseModels
{
    public $id;
    public $entryDate;
    public $amount;
    public $amountCurrency;
    public $currencyIso;
    public $currencyRate;
    public $voucherNo;
    public $accountsId;
    public $vat_codesId;
    public $text;
    public $additionalText;
    public $contactsId;
    public $documentsId;
    public $discountPercent;
    public $articleNo;
    public $quantity;
    public $unit;
    public $dueDate;
    public $entryType;
    public $prime;
    public $status;
    public $vatJournalId;
    public $documentsSubId;
    public $unitPrice;
    public $documentPosition;
    public $itemsId;
    public $vatSettled;
}

class EntriesTypes extends BasicEnum
{
    const id              	= dataType::INT;
    const entryDate       	= dataType::DATE;
    const amount          	= dataType::DECIMAL;
    const amountCurrency  	= dataType::DECIMAL;
    const currencyIso     	= dataType::ENUM;
    const currencyRate    	= dataType::DECIMAL;
    const voucherNo       	= dataType::VARCHAR;
    const accountsId      	= dataType::INT;
    const vat_codesId     	= dataType::INT;
    const text            	= dataType::VARCHAR;
    const additionalText  	= dataType::TEXT;
    const contactsId      	= dataType::INT;
    const documentsId     	= dataType::INT;
    const discountPercent 	= dataType::DECIMAL;
    const articleNo       	= dataType::VARCHAR;
    const quantity        	= dataType::DECIMAL;
    const unit            	= dataType::VARCHAR;
    const dueDate         	= dataType::DATE;
    const entryType       	= dataType::ENUM;
    const prime           	= dataType::ENUM;
    const status          	= dataType::ENUM;
    const vatJournalId    	= dataType::INT;
    const documentsSubId  	= dataType::INT;
    const unitPrice       	= dataType::DECIMAL;
    const documentPosition	= dataType::INT;
    const itemsId         	= dataType::INT;
    const vatSettled      	= dataType::ENUM;
}

abstract class CurrencyIso extends BasicEnum
{
    const dkk	= 'dkk';
    const eur	= 'eur';
}

abstract class EntryType extends BasicEnum
{
    const main  	= 'main';
    const contra	= 'contra';
    const vat   	= 'vat';
}

abstract class Prime extends BasicEnum
{
    const no 	= 'no';
    const yes	= 'yes';
}

abstract class Status extends BasicEnum
{
    const draft 	= 'draft';
    const posted	= 'posted';
}

abstract class VatSettled extends BasicEnum
{
    const yes	= 'yes';
    const no 	= 'no';
}