<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 30-11-2020
 * Time: 10:11
 * Path: /secure/com/series/Series.php
 */

namespace OrSdk\Models\Com\Series;

use OrSdk\Util\dataType;
use OrSdk\Util\BasicEnum;

use OrSdk\Models\BaseModels;

class Series extends BaseModels
{
    public $id;
    public $name;
    public $nextNo;
    public $prefix;
    public $postfix;
    public $zeroPad;
}

class SeriesTypes extends BasicEnum
{
    const id     	= dataType::INT;
    const name   	= dataType::VARCHAR;
    const nextNo 	= dataType::INT;
    const prefix 	= dataType::VARCHAR;
    const postfix	= dataType::VARCHAR;
    const zeroPad	= dataType::INT;
}