<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 12-09-2019
 * Time: 12:09
 * Path: /secure/com/vat_codes/VatCodes.php
 */

namespace OrSdk\Models\Com\VatCodes;

use OrSdk\Util\dataType;
use OrSdk\Util\BasicEnum;

use OrSdk\Models\BaseModels;


class VatCodes extends BaseModels
{
    public $id;
    public $code;
    public $name;
    public $rate;
    public $accountsId;
    public $type;
    public $contraAccountsId;
    public $vatSection;
    public $active;
}

class VatCodesTypes extends BasicEnum
{
    const id              	= dataType::INT;
    const code            	= dataType::VARCHAR;
    const name            	= dataType::VARCHAR;
    const rate            	= dataType::DECIMAL;
    const accountsId      	= dataType::INT;
    const type            	= dataType::ENUM;
    const contraAccountsId	= dataType::INT;
    const vatSection      	= dataType::ENUM;
    const active          	= dataType::ENUM;
}

abstract class Type extends BasicEnum
{
    const expense	= 'expense';
    const income 	= 'income';
}

abstract class VatSection extends BasicEnum
{
    const A1	= 'A1';
    const A2	= 'A2';
    const B1	= 'B1';
    const B2	= 'B2';
    const B3	= 'B3';
    const C1	= 'C1';
}

abstract class Active extends BasicEnum
{
    const yes	= 'yes';
    const no 	= 'no';
}