<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 12-09-2019
 * Time: 12:09
 * Path: /secure/com/vat_codes/VatCodes.php
 */

namespace OrSdk\Models\Com\VatCodes;

use OrSdk\Models\BaseModels;


class VatCodes extends BaseModels
{
    public $id;
    public $code;
    public $name;
    public $rate;
    public $accountsId;
    public $type;
    public $contraAccountsId;
    public $vatSection;
    public $active;
}