<?php
/**
 * Copyright (c) 2021. Fakturaservice A/S - All Rights Reserved 
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential
 * Written by Torben Wrang Laursen <twl@fakturaservice.dk>, February 2021
 */

/**
 * Generated by GenerateModel.php script.
 * User: twl
 * Date: 11-02-2020
 * Time: 01:02
 * Path: /secure/com/periods/Periods.php
 */

namespace OrSdk\Models\Com\Periods;

use OrSdk\Util\dataType;
use OrSdk\Util\BasicEnum;

use OrSdk\Models\BaseModels;


class Periods extends BaseModels
{
    public $id;
    public $periodStart;
    public $periodEnd;
    public $state;
    public $vatInterval;
    public $financeVoucherNo;
    public $prefixFinanceVoucherNo;
    public $postfixFinanceVoucherNo;
    public $zeroPadFinanceVoucherNo;
}

class PeriodsTypes extends BasicEnum
{
    const id                     	= dataType::INT;
    const periodStart            	= dataType::DATE;
    const periodEnd              	= dataType::DATE;
    const state                  	= dataType::ENUM;
    const vatInterval            	= dataType::ENUM;
    const financeVoucherNo       	= dataType::INT;
    const prefixFinanceVoucherNo 	= dataType::VARCHAR;
    const postfixFinanceVoucherNo	= dataType::VARCHAR;
    const zeroPadFinanceVoucherNo	= dataType::INT;
}

abstract class State extends BasicEnum
{
    const open  	= 'open';
    const closed	= 'closed';
}

abstract class VatInterval extends BasicEnum
{
    const _6M	= '6M';
    const _3M	= '3M';
    const _1M	= '1M';
    const _12M	= '12M';
}